name: ATM Unit Tests CI  # Optional workflow name

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Checkout the repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # You can use 3.10 or 3.11 based on your preference

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure dependencies are installed from your requirements.txt

      - name: Run tests with unittest
        run: |
          python -m unittest discover  # Run all unittests in the current directory
